spring:
  application:
    name: kanboard-api

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGenerationThatIsLongEnoughForHMAC256}
    expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}

logging:
  level:
    com.taskmanager.kanboard: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
