spring:
  application:
    name: kanboard-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/kanboard}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGenerationThatIsLongEnoughForHMAC256}
    expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}

logging:
  level:
    com.taskmanager.kanboard: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
