spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

logging:
  level:
    root: WARN
    com.taskmanager.kanboard: INFO
    org.springframework.security: WARN

management:
  endpoint:
    health:
      show-details: when_authorized
